Update template.xml.in
notAperson535/OneClick-macOS-Simple-KVM pull request #55
Opened 2022-11-11 14:49 UTC by therealrem

Adding those quemu args and following with this guide (https://github.com/MobCode100/Dastux/blob/main/VoodooHDA-QEMU-KVM.md) will enable audio playback without passthrough in the macOS VM (tested with Ventura).

2022-11-11 18:07 UTC, notAperson535 requested changes
Could you add these changes to basic.sh too?

2022-11-12 09:57 UTC, therealrem commented
Also removed ICH9 audio which is useless in template.xml.in

2022-11-12 10:19 UTC, therealrem commented
> Could you add these changes to basic.sh too?

done :)

2022-11-12 11:02 UTC, therealrem commented
@notAperson535 Please wait a bit, sound is actually NOT working with basic.sh despite changes I've made. Looking for a solution...

2022-11-12 11:03 UTC, notAperson535 commented
> @notAperson535 Please wait a bit, sound is actually NOT working with basic.sh despite changes I've made. Looking for a solution...

Ok

2022-11-12 14:52 UTC, therealrem commented
@notAperson535

OK got it sorted. Both updated files are now fine.

**If you want sound inside your macOS VM, whether with qemu or libvirt/virt-manager :**

1) Disable System Integrity Protection (SIP) : 
- On boot, select the recovery partition (arrow keys) and press enter to boot into it.
- Run the below command (choose either one) :
csrutil disable
# or
csrutil enable --without kext
- Reboot your VM in macOS.

2) Download latest VoodooHDA kext from here : https://sourceforge.net/projects/voodoohda/

3) Open the terminal application, run :
sudo cp -R Downloads/VoodooHDA.kext /Library/Extensions (enter password when prompted).

4) Wait a few seconds, a popup should appear => "Open Security Preferences".
4a) If no popup, run : sudo kextutil -v /Library/Extensions/VoodooHDA.kext

5) If you did not click on the "Open Security Preferences", go to "Security & Privacy" section inside "System Settings application".

6) Allow "VoodooHDA" and restart.

2022-11-12 15:06 UTC, notAperson535 commented
> Maybe those steps should be added in the Install Guide :-)
Exactly what I was thinking. Merging now.

2022-11-12 16:22 UTC, notAperson535 approved these changes

2022-11-12 16:22 UTC, merged